/** @format */

import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import { GlobalStyle } from '../styles/global-style';
import { theme } from '../styles/theme';
import 'antd/dist/antd.css';
function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Kim And Jang</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/frog.png' />
            </Head>
            <GlobalStyle />
            <ThemeProvider theme={theme}>
                <Component {...pageProps} />
            </ThemeProvider>
        </>
    );
}
export default MyApp;
